service:
  categories: http://categories/categories
  products: http://products/products
  redis: ${SPRING_REDIS_URL}

server:
  port: 8092

spring:
  application:
    name: catalog
  profiles:
    active: prod

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"