server:
  port: 8100

spring:
  application:
    name: zuul
  profiles:
    active: prod

# Internally, Zuul uses Netflix Ribbon to look up for all instances
  # of the service from the service discovery (Eureka Server).
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

# Each request received by Zuul is forwarded to a different instance in a round robin fashion.
 # If we start another instance and register it in Eureka, Zuul will register it automatically and start forwarding requests to it:
zuul:
  sensitive-headers: Cookie,Set-Cookie
  ignoredServices: '*'
  prefix: /api
  routes:
    oauth:
      path: /oauth/**
      serviceId: users
      sensitive-headers:
      stripPrefix: false
    catalog:
      path: /catalog/**
      serviceId: catalog
      sensitive-headers:
      stripPrefix: false
    users:
      path: /users/**
      serviceId: users
      sensitive-headers:
      stripPrefix: false

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    resource:
      jwt:
        key-value: 123