server:
  port: 8094

spring:
  application:
    name: categories
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

